# -*- coding: utf-8 -*-
"""Air_BnB_EDA_J_Lehrer_1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1803mO7-bjbwanO9oFAShoGIrOa-P85ER

# Dependencies and Libraries
"""

# importing dependencies

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px

# Setting seed for reproducibility

np.random.seed(42)
PYTHONHASHSEED = 0

"""# Listings Dataset EDA"""

# Load the listings dataset
dataset_path = '/content/listings.csv'

df_list = pd.read_csv(dataset_path)

df_list.head(100)

# information about the dataset
df_list.info(), df_list.shape

df_list = df_list.replace(-200, None)
df_list = df_list.replace('nan nan', None)

df_list.isnull().sum()

df_list = df_list.drop(columns=['amenities','instant_bookable','last_review','first_review','has_availability','host_verifications','host_is_superhost','host_acceptance_rate','host_response_rate','host_identity_verified','host_has_profile_pic','host_response_time','host_since','reviews_per_month','id','listing_url','scrape_id','last_scraped','source','name','description','neighborhood_overview','picture_url','host_id','host_url','host_name','host_location','host_about','host_thumbnail_url','host_picture_url','host_neighbourhood','neighbourhood','neighbourhood_cleansed','neighbourhood_group_cleansed','latitude','longitude','property_type','room_type','bathrooms_text','calendar_updated','calendar_last_scraped','license'])

df_list['price'] = df_list['price'].str.replace('$', '')
df_list['price'] = df_list['price'].str.replace(',', '')
df_list['price'] = df_list['price'].astype('float')

df_list.info(), df_list.shape

# data visualization functions

def visualizeScatter(df_list, x, y, fill, title):
    fig = px.scatter(df_list,
    x=x,
    y=y,
    color=fill,
    #     facet_row=fill,
    title=title)

    fig.show()

def visualizeFilledArea(x, y, fill, hd):
    fig = px.area(df_list,
    x=x,
    y=y,
    color=fill,
    hover_data=[hd])

    fig.show()

def visualizeLineCharts(df_list, columns, x1, title):
    columns = columns

    fig = go.Figure([{
    'x': df_list[x1],
    'y': df_list[col],
    'name': col
    }  for col in columns], layout=go.Layout(title=go.layout.Title(text=title)))

    fig.show()

def displayHeatMap(dim1, dim2, title, df_list):
    # Create a mask to hide the upper triangle (excluding the diagonal)
    mask = np.triu(np.ones_like(corr, dtype=bool))
    fig=plt.figure(figsize=(dim1,dim2))
    plt.title(title)
    sns.heatmap(df_list, annot= True, mask=mask, cmap='flare')

corr = df_list.corr()
displayHeatMap(33, 33, 'Correlation Between Air BnB Attributes', corr)

"""# Neighbourhoods Dataset EDA"""

# Load the neighbourhoods dataset
dataset_path = '/content/neighbourhoods.csv'

df_neigh = pd.read_csv(dataset_path)

df_neigh.head(100)

# information about the dataset
df_neigh.info(), df_neigh.shape

"""# Reviews Dataset EDA"""

# Load the reviews dataset
dataset_path = '/content/reviews.csv'

df_review = pd.read_csv(dataset_path)

df_review.head(100)

# information about the dataset
df_review.info(), df_review.shape

"""# Calendar Dataset EDA"""

# Load the calendar dataset
dataset_path = '/content/calendar.csv'

df_cal = pd.read_csv(dataset_path)

df_cal.head(100)

# information about the dataset
df_cal.info(), df_cal.shape